apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus-pod
  template:
    metadata:
      labels:
        app: event-bus-pod
    spec:
      containers:
      - name: posts
        image: harsh253/event-bus:latest
  