apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-pod
  template:
    metadata:
      labels:
        app: posts-pod
    spec:
      containers:
      - name: posts
        image: harsh253/posts:latest

---
apiVersion: v1
kind: Service
metadata:
  name: post-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: posts-pod
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000